applications:
  - image: gcr.io/$PROJECT_ID/foo
    source_owner: sakajunquality
    source_name: example-app
    manifest_owner: sakajunquality
    manifest_name: example-deployment
    manifest_base_branch: master
    manifests:
      - env: dev
        branch: dev
        commit_without_pr: true
        files:
          - overlays/dev/deployment.yaml
      - env: qa
        files:
          - overlays/qa/deployment.yaml
        filters:
          include_prefixes:
            - qa # qa.*
            - release # release.*
      - env: staging
        files:
          - overlays/staging/deployment.yaml
        filters:
          include_prefixes:
            - v # v.*
      - env: production
        files:
          - overlays/production/deployment.yaml
        filters:
          include_prefixes:
            - v # v.*
        pr_body: |
          THIS IS PRODUCTION

git_author:
  name: sakajunquality
  email: test@sakajunquality.dev

default_branch: main
