name: Publish nightly Docker image
on:
  push:
    branches:
    - main
jobs:
  push:
    name: Push Docker image to GitHub Docker Registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
      with:
        push: true
        tags: docker.pkg.github.com/ubie-oss/flow/flow:latest
